# application.yml

spring:
  config:
    import: "optional:file:./src/main/resources/application.secret.yml"

  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    show-sql: true

